/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DatasourceConfig } from './datasourceConfig';

export type CreateDatasourceBody = {
  /** @minLength 2 */
  name: string;
  config: DatasourceConfig;
};
