/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Datasource } from './datasource';

export type CreateDatasource200 = {
  data: Datasource;
};
