/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DatasourceBigQueryConfigType } from './datasourceBigQueryConfigType';
import type { DatasourceBigQueryConfigServiceAccountJson } from './datasourceBigQueryConfigServiceAccountJson';

export interface DatasourceBigQueryConfig {
  type: DatasourceBigQueryConfigType;
  /**
   * The project ID must contain only lowercase letters, numbers, and hyphens.
   * @minLength 6
   * @maxLength 30
   * @pattern ^[a-z0-9-]+$
   */
  projectId: string;
  /** The service account JSON must be a valid JSON object. */
  serviceAccountJson: DatasourceBigQueryConfigServiceAccountJson;
}
