/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DatasourceSnowflakeConfigType } from './datasourceSnowflakeConfigType';

export interface DatasourceSnowflakeConfig {
  type: DatasourceSnowflakeConfigType;
  account: string;
  username: string;
  password: string;
  warehouse: string;
}
