/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type DatasourceBigQueryRedactedConfigType = typeof DatasourceBigQueryRedactedConfigType[keyof typeof DatasourceBigQueryRedactedConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasourceBigQueryRedactedConfigType = {
  bigquery: 'bigquery',
} as const;
