/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DatasourceSnowflakeRedactedConfigType } from './datasourceSnowflakeRedactedConfigType';

export interface DatasourceSnowflakeRedactedConfig {
  type: DatasourceSnowflakeRedactedConfigType;
  account: string;
  username: string;
  warehouse: string;
}
