/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type DatasourceSnowflakeConfigType = typeof DatasourceSnowflakeConfigType[keyof typeof DatasourceSnowflakeConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasourceSnowflakeConfigType = {
  snowflake: 'snowflake',
} as const;
