/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { DatasourceBigQueryRedactedConfigType } from './datasourceBigQueryRedactedConfigType';

export interface DatasourceBigQueryRedactedConfig {
  type: DatasourceBigQueryRedactedConfigType;
  /**
   * The project ID must contain only lowercase letters, numbers, and hyphens.
   * @minLength 6
   * @maxLength 30
   * @pattern ^[a-z0-9-]+$
   */
  projectId: string;
}
