/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { DatasourceRedactedConfig } from './datasourceRedactedConfig';
import type { DatasourceLastIndexTime } from './datasourceLastIndexTime';
import type { DatasourceLastIndexStart } from './datasourceLastIndexStart';
import type { DatasourceLastIndexError } from './datasourceLastIndexError';
import type { DatasourceIndexStartTime } from './datasourceIndexStartTime';
import type { DatasourceIndexEndTime } from './datasourceIndexEndTime';
import type { DatasourceIndexStatus } from './datasourceIndexStatus';
import type { DatasourceIndexError } from './datasourceIndexError';

export interface Datasource {
  id: Uuid;
  name: string;
  config: DatasourceRedactedConfig;
  lastIndexTime: DatasourceLastIndexTime;
  lastIndexStart: DatasourceLastIndexStart;
  lastIndexError: DatasourceLastIndexError;
  indexStartTime: DatasourceIndexStartTime;
  indexEndTime: DatasourceIndexEndTime;
  indexStatus: DatasourceIndexStatus;
  indexError: DatasourceIndexError;
  createdAt: string;
  updatedAt: string;
}
