/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Table } from './table';
import type { Meta } from './meta';

export type GetTables200 = {
  data: Table[];
  meta?: Meta;
};
