/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type InvitationRole = typeof InvitationRole[keyof typeof InvitationRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvitationRole = {
  admin: 'admin',
  member: 'member',
} as const;
