/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Organization } from './organization';
import type { InvitationRole } from './invitationRole';

export interface Invitation {
  id: Uuid;
  organizationId: Uuid;
  organization: Organization;
  email: string;
  role: InvitationRole;
  createdAt: string;
  updatedAt: string;
}
