/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Organization } from './organization';
import type { User } from './user';
import type { MemberRole } from './memberRole';

export interface Member {
  userId: string;
  organizationId: string;
  organization: Organization;
  user: User;
  role: MemberRole;
  createdAt: string;
  updatedAt: string;
}
