/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type MessageEventEndType = typeof MessageEventEndType[keyof typeof MessageEventEndType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageEventEndType = {
  message_event_end: 'message_event_end',
} as const;
