/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type MessageEventChunkType = typeof MessageEventChunkType[keyof typeof MessageEventChunkType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageEventChunkType = {
  message_event_chunk: 'message_event_chunk',
} as const;
