/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type MessageEventEndData = {
  id: string;
  /** @maxLength 1048576 */
  content: string;
};
