/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { MessageRole } from './messageRole';
import type { MessageType } from './messageType';

export interface Message {
  id: string;
  role: MessageRole;
  type: MessageType;
  /** @maxLength 1048576 */
  content: string;
  createdAt: string;
}
