/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type MessageEventStartType = typeof MessageEventStartType[keyof typeof MessageEventStartType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageEventStartType = {
  message_event_start: 'message_event_start',
} as const;
