/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { MessageEventStart } from './messageEventStart';
import type { MessageEventChunk } from './messageEventChunk';
import type { MessageEventEnd } from './messageEventEnd';

export type MessageEvent = MessageEventStart | MessageEventChunk | MessageEventEnd;
