/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { OrganizationTier } from './organizationTier';
import type { OrganizationTrialEnd } from './organizationTrialEnd';

export interface Organization {
  id: Uuid;
  name: string;
  tier: OrganizationTier;
  trialEnd: OrganizationTrialEnd;
  requestUpgrade: boolean;
  createdAt: string;
  updatedAt: string;
}
