/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface Query {
  id: Uuid;
  name: string;
  text: string;
  shared: boolean;
  createdAt: string;
  updatedAt: string;
}
