/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { QueryResult } from './queryResult';
import type { Meta } from './meta';

export type RunQuery200 = {
  data: QueryResult;
  meta?: Meta;
};
