/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { TableColumnsItem } from './tableColumnsItem';

export interface Table {
  name: string;
  columns: TableColumnsItem[];
  metadata?: unknown;
  updatedAt: string;
}
