/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { UserFirstName } from './userFirstName';
import type { UserLastName } from './userLastName';

export interface User {
  id: Uuid;
  firstName: UserFirstName;
  lastName: UserLastName;
  email: string;
  createdAt: string;
  updatedAt: string;
}
