#!/usr/bin/env node
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cipher42 API Documentation
 * Cipher42 API Documentation
 * OpenAPI spec version: 1.0.0
 */

import {
  McpServer
} from '@modelcontextprotocol/sdk/server/mcp.js';
  
import {
  StdioServerTransport
} from '@modelcontextprotocol/sdk/server/stdio.js';  

import {
  getCurrentUserHandler,
  getUserByIdHandler,
  updateUserByIdHandler,
  getUserMemebershipsByIdHandler,
  getUserInvitationsHandler,
  createDatasourceHandler,
  getDatasourcesHandler,
  getDatasourceByIdHandler,
  deleteDatasourceByIdHandler,
  runQueryHandler,
  getSchemasHandler,
  getTablesHandler
} from './handlers';
import {
  getUserByIdParams,
  updateUserByIdParams,
  updateUserByIdBody,
  getUserMemebershipsByIdParams,
  getUserInvitationsParams,
  createDatasourceParams,
  createDatasourceBody,
  getDatasourcesParams,
  getDatasourceByIdParams,
  deleteDatasourceByIdParams,
  runQueryParams,
  runQueryBody,
  getSchemasParams,
  getTablesParams
} from './tool-schemas.zod';

const server = new McpServer({
  name: 'cipher42APIDocumentationServer',
  version: '1.0.0',
});


server.tool(
  'getCurrentUser',
  'Get current user',
  getCurrentUserHandler
);


server.tool(
  'getUserMemebershipsById',
  'Get user memberships by ID',
  {
    pathParams: getUserMemebershipsByIdParams
  },
  getUserMemebershipsByIdHandler
);


server.tool(
  'getDatasources',
  'Get datasources',
  {
    pathParams: getDatasourcesParams
  },
  getDatasourcesHandler
);

server.tool(
  'runQuery',
  'Run query',
  {
    pathParams: runQueryParams,
    bodyParams: runQueryBody
  },
  runQueryHandler
);

server.tool(
  'getSchemas',
  'Get schemas for a datasource',
  {
    pathParams: getSchemasParams
  },
  getSchemasHandler
);

server.tool(
  'getTables',
  'Get tables for a schema',
  {
    pathParams: getTablesParams
  },
  getTablesHandler
);

const transport = new StdioServerTransport();

server.connect(transport).then(() => {
  console.error('MCP server running on stdio');
}).catch(console.error);
